### ISSUE TITLE
Splash, 인증(로그인, 회원가입) 화면 구현

### ISSUE THREAD

**Issue by jiwon2724** [Seoul-DiningTable/Seoul-DiningTable-Android#1]
# Description
Splash, 인증(로그인, 회원가입) 화면 구현

# TODO

- [x] Splash 화면 구현
    - 일정시간 대기 후 로그인 화면으로 이동
- [x] 로그인 화면 구현
    - 네이버, 카카오 로그인 구현
- [x] 닉네임 입력 화면, 사장님 인증화면 구현

# ETC
기타사항
